export const schools: string[] = [
    "University at Buffalo - SUNY",
    "Buffalo State University - SUNY",
    `Aalto University`,
    `Aarhus University`,
    `Abertay University`,
    `Academy at Palumbo`,
    `Academy of Technology`,
    `Achariya College of Engineering Technology`,
    `Adelphi University`,
    `AGH University of Science and Technology`,
    `Agnes Scott College`,
    `Alagappa Chettiar Government College of Engineering and Technology`,
    `Albany Medical College`,
    `Albany State University (GA)`,
    `Albright College`,
    `Alfa College`,
    `Aligarh Muslim University`,
    `Ambala College of Engineering and Applied Research`,
    `American Heritage School`,
    `"American River College, California"`,
    `American University in Dubai`,
    `"American University, Washington, D.C."`,
    `Amherst College`,
    `Appalachian State University`,
    `APS College of Engineering`,
    `Arcadia University`,
    `Arizona State University`,
    `Arya College of Engineering & I.T.`,
    `"Asia Pacific University of Information & Technology, Kuala Lumpur"`,
    `Asian School of Business Management (ASBM University)`,
    `Assam Downtown University`,
    `"Assam University, Silchar"`,
    `Aston University`,
    `Atlanta Metropolitan State College`,
    `Atlantic Cape Community College`,
    `Atma Ram Sanatan Dharma College`,
    `ATME College of Engineering`,
    `Auburn University`,
    `Aurora Group of Institutions`,
    `Austin Community College District`,
    `B.M.S College Of Engineering`,
    `Babson College`,
    `Badruka Educational Society`,
    `Bahria University Lahore Campus`,
    `Ball State University`,
    `Bangalore University`,
    `Bard College`,
    `Barnard College`,
    `Barton College`,
    `"Baruch College, CUNY"`,
    `Baton Rouge Community College`,
    `Bauman Moscow State Technical University`,
    `Bayview Secondary School`,
    `Beihang University`,
    `"Bellevue College, Washington"`,
    `Benedictine College`,
    `Benha University`,
    `Bennett College`,
    `Bennett University (Times of India Group)`,
    `Bentley University`,
    `Berea College`,
    `Bergen Community College`,
    `Bergen County Academies`,
    `Berkshire Community College`,
    `Bhagalpur College of Engineering`,
    `Bharathiar University`,
    `Bharati Vidyapeeth's College of Engineering`,
    `Bilkent University`,
    `Binghamton University`,
    `"Birkbeck, University of London"`,
    `Birmingham City University`,
    `Blinn College`,
    `Bloomsburg University of Pennsylvania`,
    `Blue Mountain Academy`,
    `BlueCrest University College`,
    `Boise State University`,
    `"Borough of Manhattan Community College, CUNY"`,
    `Boston College`,
    `Boston Latin School`,
    `Boston University`,
    `Boston University Metropolitan College`,
    `Bourne Grammar School`,
    `Bournemouth University`,
    `Bowdoin College`,
    `Bowie State University`,
    `Bowling Green State University`,
    `Brampton Centennial Secondary School`,
    `Brandeis University`,
    `Briar Cliff University`,
    `Bridgewater State University`,
    `Brigham Young University`,
    `Brno University of Technology`,
    `Brock University`,
    `"Bronx Community College, CUNY"`,
    `Brookdale Community College`,
    `"Brooklyn College, CUNY"`,
    `Brown University`,
    `Brunel University London`,
    `Bryn Athyn College`,
    `Bryn Mawr College`,
    `Bucknell University`,
    `Bucks County Community College`,
    `Business Academy Aarhus`,
    `C.V. Raman College of Engineering`,
    `Cabrini University`,
    `Cadbury Sixth Form College`,
    `Cairn University`,
    `Caldwell University`,
    `"California Polytechnic State University, San Luis Obispo"`,
    `"California State Polytechnic University, Pomona"`,
    `"California State University, Bakersfield"`,
    `"California State University, Channel Islands"`,
    `"California State University, Chico"`,
    `"California State University, Dominguez Hills"`,
    `"California State University, East Bay"`,
    `"California State University, Fresno"`,
    `"California State University, Fullerton"`,
    `"California State University, Humboldt"`,
    `"California State University, Long Beach"`,
    `"California State University, Los Angeles"`,
    `"California State University, Maritime"`,
    `"California State University, Monterey Bay"`,
    `"California State University, Northridge"`,
    `"California State University, Sacramento"`,
    `"California State University, San Bernardino"`,
    `"California State University, San Diego"`,
    `"California State University, San Francisco"`,
    `"California State University, San Jose"`,
    `"California State University, San Luis Obispo"`,
    `"California State University, San Marcos"`,
    `"California State University, Sonoma"`,
    `"California State University, Stanislaus"`,
    `California University of Pennsylvania`,
    `Calvin College`,
    `Camden County College`,
    `Canyon Crest Academy`,
    `Cardiff Metropolitan University`,
    `Carleton College`,
    `Carleton University`,
    `Carnegie Mellon University`,
    `Carthage College`,
    `Cascadia College`,
    `Case Western Reserve University`,
    `Catholic University of America`,
    `Cedarville University`,
    `Central Connecticut State University`,
    `Central Peel Secondary School`,
    `Central Texas College`,
    `Cerritos College`,
    `Chalmers University of Technology`,
    `Champlain College`,
    `Chandigarh College Of Engineering & Technology (CCET)`,
    `Chandigarh University`,
    `Chaparral Star Academy`,
    `Charotar University Of Science And Technology (CHAURSAT)`,
    `Chattahoochee Technical College`,
    `Chestnut Hill College`,
    `Cheyney University`,
    `Chinguacousy Secondary School`,
    `Chitkara University`,
    `Christ College of Engineering and Technology`,
    `Christ Knowledge City`,
    `Christ University`,
    `Christ University Faculty of Engineering`,
    `Cincinnati State Technical and Community College`,
    `Citrus College`,
    `City College of San Francisco`,
    `City University London`,
    `Claremont McKenna College`,
    `Clarion University of Pennsylvania`,
    `Clark Atlanta University`,
    `Clark University`,
    `Clarkson University`,
    `Clayton State University`,
    `Clemson University`,
    `Cleveland State University`,
    `Clifton Public Highschool`,
    `"CMR College of Engineering and Technology,  Hyderabad"`,
    `CMR Technical Campus`,
    `Cochin College of Engineering and Technology`,
    `Cochin University College of Engineering Kuttanad`,
    `Cochin University of Science and Technology`,
    `Cochin University of Science And Technology`,
    `CODE University of Applied Sciences Berlin`,
    `Coe College`,
    `Colgate University`,
    `College of Agricultural Engineering and Post Harvest Technology (CAEPHT)`,
    `"College of Agriculture, Central Agricultural University"`,
    `College of Charleston`,
    `College of DuPage`,
    `College of Engineering & Management Punnapra`,
    `"College of Engineering and Management, Kolaghat"`,
    `College of Engineering Chengannur`,
    `"College of Engineering, Pune"`,
    `"College of Staten Island, CUNY"`,
    `"College of Technology & Engineering, Udaipur"`,
    `College of Westchester`,
    `Colorado School of Mines`,
    `Columbia Secondary School`,
    `Columbia University`,
    `Columbus College of Art and Design`,
    `Columbus State Community College`,
    `Comenius University`,
    `Community College of Allegheny County`,
    `Community College of Baltimore County`,
    `Community College of Philadelphia`,
    `Community College of Rhode Island`,
    `Concord Academy`,
    `Concordia University`,
    `Concordia University Ann Arbor`,
    `Concordia University Chicago`,
    `Concordia University Irvine`,
    `Concordia University Nebraska`,
    `Concordia University St. Paul`,
    `Concordia University Texas`,
    `Concordia University Wisconsin`,
    `Conestoga College`,
    `Connecticut College`,
    `"Conroe ISD Academy of Science and Technology, Texas"`,
    `Cooper Union`,
    `Cornell College`,
    `Cornell University`,
    `County College of Morris`,
    `Covenant University`,
    `Coventry University`,
    `Cranbrook Schools`,
    `Cranfield University`,
    `Cumberland County College`,
    `D.J. College of Engineering & Technology`,
    `Dalhousie University`,
    `Dartmouth College`,
    `Davidson College`,
    `Dawson College`,
    `Dayananda Sagar University`,
    `De Anza College`,
    `Delaware County Community College - Downingtown`,
    `Delaware County Community College - Exton`,
    `Delaware County Community College - Main Campus (Marple)`,
    `Delaware County Community College - Phoenixville`,
    `Delaware County Community College - Sharon Hill`,
    `Delaware County Community College - Upper Darby`,
    `Delaware County Community College - West Grove`,
    `Delaware State University`,
    `Delaware Technical Community College`,
    `Delaware Valley Academy of Medical and Dental Assistants`,
    `Delaware Valley University`,
    `Delft University of Technology`,
    `Denison University`,
    `DePaul University`,
    `DePauw University`,
    `Des Moines Area Community College`,
    `DeSales University`,
    `Devry University - Philadelphia Center City`,
    `Dharmsinh Desai University`,
    `Diablo Valley College`,
    `Dickinson College`,
    `DIT University`,
    `Don Bosco College of Engineering`,
    `Don Bosco College of Engineering and Technology`,
    `Doon College of Engineering & Technology`,
    `"Dr. A.P.J. Abdul Kalam Technical University, Lucknow"`,
    `Dr. Babasaheb Ambedkar Marathwada University`,
    `"Dr. Harisingh Gour University, Sagar University"`,
    `Dr. SJS Paul Memorial College of Engineering and Technology (CIT)`,
    `Drake University`,
    `Drew University`,
    `Drexel University`,
    `Duke University`,
    `Duquesne University`,
    `Durham College`,
    `Durham University`,
    `Dwarkadas J. Sanghvi College of Engineering`,
    `Dwight-Englewood School`,
    `Earl of March Secondary School`,
    `Earlham College`,
    `East Central University`,
    `East Chapel Hill High Schoo`,
    `East Los Angeles College`,
    `East Point College of Engineering and Technology`,
    `EASTERN Center for Arts and Technology`,
    `Eastern Michigan University`,
    `Eastern University - St. Davids`,
    `Eastern Washington University`,
    `Eckerd College`,
    `Edinburgh Napier University`,
    `Edison Academy`,
    `Elgin Academy`,
    `Elon University`,
    `Embry-Riddle Aeronautical University`,
    `Emory University`,
    `"Entrepreneurship Development Center, MIT, Pune"`,
    `"Entreprpeneurship Development Cell, University of Kerala"`,
    `Episcopal Academy`,
    `EPITECH Bordeaux`,
    `Er.Perumal Manimekalai College of Engineering`,
    `Erasmus Hogeschool Brussel`,
    `Erie Community College`,
    `Evergreen Valley College`,
    `Fachhochschule Dortmund`,
    `"Faculty Of Engineering & Technology, Gurukula Kangri Vishwavidyalaya"`,
    `Faculty of science / Ibn Tofail University`,
    `Fairfield University`,
    `Fairleigh Dickinson University`,
    `Farmingdale State College`,
    `Finolex Academy of Management and Technology`,
    `Fitchburg State University`,
    `Florida Agricultural & Mechanical (A&M) University`,
    `Florida Atlantic University`,
    `Florida Gulf Coast University`,
    `Florida International University`,
    `Florida Polytechnic University`,
    `Florida State University`,
    `Fontys Hogeschool`,
    `Foothill College`,
    `Fordham University`,
    `Fort Scott Community College`,
    `Foundation Collegiate Academy`,
    `Fr. Conceicao Rodrigues College of Engineering`,
    `Francis Holland School`,
    `Franklin Learning Center - Philadelphia`,
    `Franklin W. Olin College of Engineering`,
    `Frederick Community College`,
    `Full Sail University`,
    `Fullerton College`,
    `George Heriot's School`,
    `George Mason University`,
    `Georgetown University`,
    `Georgia State University`,
    `Germantown Friends School`,
    `Grand Rapids Community College`,
    `Grand Valley State University`,
    `Graphic Era University`,
    `Green River College`,
    `Greenwood College School`,
    `GZS Campus College of Engineering & Technology`,
    `H.N. Werkman College`,
    `Haaga-Helia University of Applied Sciences`,
    `Hamilton College`,
    `Hamline University`,
    `Hampshire College`,
    `Hampton University`,
    `HAN University of Applied Sciences`,
    `Hanze University of Applied Sciences`,
    `Harcum College`,
    `Harper College`,
    `Harrisburg Area Community College`,
    `Harrisburg University - Harrisburg Campus`,
    `Harrisburg University - Philadelphia Campus`,
    `Harvard Medical School`,
    `Harvard University`,
    `Harvey Mudd University`,
    `Hasso-Plattner-Institut Academy`,
    `Haverford College`,
    `Head-Royce School`,
    `Heartland Community College`,
    `Helwan University`,
    `Herguan University`,
    `Het Baarnsch Lyceum`,
    `Hillsborough Community College`,
    `Hindustan College of Science & Technology`,
    `Hiram College`,
    `HKBK College of Engineering`,
    `Hofstra University`,
    `Hogeschool Thomas More`,
    `Hogeschool van Amsterdam`,
    `Holton-Arms School`,
    `Holy Family University`,
    `Hong Kong University of Science and Technology`,
    `Hood College`,
    `Horace Mann School`,
    `"Hostos Community College, CUNY"`,
    `Houston Community College`,
    `Howard University`,
    `Hudson County Community College`,
    `Hudson Valley Community College`,
    `"Hunter College, CUNY"`,
    `Huron Heights Secondary School`,
    `Hussian School of Art`,
    `Iliria College`,
    `Illinois State University`,
    `Impact College of Engineering and Applied Science`,
    `Imperial College London`,
    `Indira Gandhi National Open University`,

    `International School of Choueifat`,
    `Iowa Central Community College`,
    `Iowa State University`,
    `Iowa Western Community College`,
    `IT University of Copenhagen`,
    `Ithaca College`,
    `"ITM University, Gwalior"`,
    `"ITM University, Vadodara"`,
    `ITMO University`,
    `"J.C. Bose University of Science and Technology, YMCA"`,
    `J.N.N College of Engineering`,
    `Jackson State University`,
    `Jacobs University Bremen`,
    `James Madison University`,
    `John Abbott College`,
    `"John Jay College of Criminal Justice, CUNY"`,
    `John Leggott College`,
    `Johns Hopkins University`,
    `Johnson & Wales University`,
    `Johnson C. Smith University`,
    `JSS Academy of Technical Education`,
    `Julia R. Masterman School`,
    `K S School of Engineering and Management`,
    `K. J. Somaiya College of Engineering`,
    `K.L. College of Engineering`,
    `K.S Rangasamy College Of Technology`,
    `K.S. School of Business Management`,
    `Kansai University`,
    `Kansas State University`,
    `Karmaveer Bhaurao Patil College of Engineering`,
    `Karpagam College of Engineering (KCE)`,
    `Kathmandu BernHardt College`,
    `Kaunas University of Technology`,
    `KCG College of Engineering`,
    `Kean University`,
    `Keele University`,
    `"Kendriya Vidyalaya, AFS, Begumpet"`,
    `Kennesaw State University`,
    `Kent State University`,
    `Kent State University at Stark`,
    `Khan Lab School`,
    `King Edward VI Five Ways School`,
    `King's College London`,
    `"Kingsborough Community College, CUNY"`,
    `Kitchener-Waterloo Collegiate & Vocational School`,
    `KLE Dr. M.S. Sheshgiri College of Engineering and Technology`,
    `KLN College of Engineering`,
    `Knox College`,
    `KNSIT`,
    `Koustuv Group Of Institutions (KISD & COEB)`,
    `"Krishi Vigyan Kendra, Durgapur"`,
    `Kristu Jayanti College`,
    `Kshatriya College of Engineering`,
    `Kumaraguru College Of Technology`,
    `Kutztown University of Pennsylvania`,
    `L D College Of Engineering Library`,
    `L. D. College of Engineering`,
    `La Roche College`,
    `La Salle University - Philadelphia`,
    `La Sierra University`,
    `Lady Doak College`,
    `Lafayette College`,
    `"LaGuardia Community College, CUNY"`,
    `Lake Braddock Secondary School`,
    `Lakshmi Narayan College of Technology (LNCT)`,
    `Lancaster University`,
    `Laval University`,
    `Lawrence Technological University`,
    `Lawrence University`,
    `Lehigh University`,
    `"Lehman College, CUNY"`,
    `Leiden University`,
    `Lewis & Clark College`,
    `Lewis University`,
    `LICET`,
    `LIM College`,
    `Lincoln Christian University`,
    `Lincoln University`,
    `Lindenwood University`,
    `Little Flowers Public Sr Secondary School`,
    `Lodz University of Technology`,
    `London Metropolitan University`,
    `London School of Economics and Political Science`,
    `Lone Star College System`,
    `Lord Krishna College of Engineering`,
    `Loughborough University`,
    `Louisiana State University`,
    `Lovely Professional University`,
    `Loyola Marymount University`,
    `Luther College`,
    `Macalester College`,
    `MacEwan University`,
    `Macomb Community College`,
    `Madison College`,
    `Maggie L. Walker Governor's School`,
    `Maharaj Vijayaram Gajapathi Raj College of Engineering (MVGRCE)`,
    `Malla Reddy College of Engineering Technology`,
    `Malnad College of Engineering`,
    `Malvern Preparatory School`,
    `Malvern Preparatory School`,
    `Manav Rachna International`,
    `Manchester Metropolitan University`,
    `Manhattan College`,
    `Manipal University`,
    `"Manipal University, Jaipur"`,
    `Manor College`,
    `Mar Athanasius College of Engineering`,
    `Marianopolis College`,
    `Marist College`,
    `Markville Secondary School`,
    `Marquette University`,
    `Marymount University`,
    `Masaryk University`,
    `Mata Gujri College`,
    `Maulana Abul Kalam Azad University of Technology`,
    `Maumee Valley Country Day School`,
    `McGill University`,
    `McMaster University`,
    `"Medgar Evers College, CUNY"`,
    `Medical University of Silesia`,
    `Menlo School`,
    `Merced College`,
    `Mercer County Community College`,
    `Mercer University`,
    `Meredith College`,
    `Messiah College`,
    `Metas Adventist School`,
    `Metropolia University of Applied Sciences`,
    `Metropolitan State University`,
    `Mewar University Chittorgarh`,
    `Miami Dade College`,
    `Miami Lakes Educational Center`,
    `Miami University`,
    `Michigan State University`,
    `Michigan Technological University`,
    `Midwood`,
    `Miles College`,
    `Milwaukee School of Engineering`,
    `Minerva University`,
    `"Minnesota State University, Mankato"`,
    `Mission College Boulevard`,
    `Mississippi State University`,
    `Mississippi University for Women`,
    `Missouri State University`,
    `Missouri University of Science and Technology`,
    `Modern Engineering and Management Studies`,
    `Mody University`,
    `Mohammed V University`,
    `Molloy College`,
    `Monmouth College`,
    `Monmouth University`,
    `Monroe Community College`,
    `Montana State University`,
    `Montclair State University`,
    `Montgomery College`,
    `Montgomery County Community College - Central Campus (Blue Bell)`,
    `Montgomery County Community College - West Campus (Pottstown)`,
    `Moore College of Art and Design`,
    `Moraine Valley Community College`,
    `Morehouse College`,
    `Morgan State University`,
    `Morris County School of Technology`,
    `Morton College`,
    `Moscrop Secondary School`,
    `Mount Holyoke College`,
    `MSME TDC PPDC Agra`,
    `Mt. San Antonio College`,
    `Muhlenberg college`,
    `MVJ College of Engineering`,
    `"Nagaland University, Dimapur Campus"`,
    `Nanyang Technological University`,
    `Narsee Monjee College of Commerce and Economics`,
    `National Research University Higher School Of Economics`,
    `National University of Singapore`,
    `Neumann University`,
    `New Horizon College of Engineering`,
    `New Jersey City University`,
    `New River Community College`,
    `"New York City College of Technology, CUNY"`,
    `New York University`,
    `New York University Abu Dhabi`,
    `Newcastle University`,
    `Niagara College`,
    `NIFT-TEA College of Knitwear Fashion`,
    `NIIT University`,
    `Nipissing University`,
    `Nirma University`,
    `NITK Science & Technology Entrepreneurs' Park (NITK-STEP)`,
    `Nizam College of Engineering Technology`,
    `Noakhali Science and Technology University`,
    `Noor-ul-Iman`,
    `Norco College`,
    `Norfolk State University`,
    `North American University`,
    `North Carolina Agricultural and Technical (A&T) State University`,
    `North Carolina Central University`,
    `North Carolina School of Science and Mathematics`,
    `North Carolina State University`,
    `North Dakota State University`,
    `North Park Secondary School`,
    `North Shore Community College`,
    `Northeastern University`,
    `Northern Arizona University`,
    `Northern Illinois University`,
    `Northern Kentucky University`,
    `Northern Michigan University`,
    `Northern Secondary School`,
    `Northern Virginia Community College`,
    `Northumbria University`,
    `Northwest Missouri State University`,
    `Northwest Vista College`,
    `Northwestern Oklahoma State University`,
    `Northwestern University`,
    `Northwood Academy/Arts School`,
    `Nottingham Trent University`,
    `NSS College of Engineering`,
    `Oakland Community College`,
    `Oakland University`,
    `Obafemi Awolowo University Ile-Ife`,
    `Oberlin College`,
    `Ocean County College`,
    `Oglethorpe University`,
    `Ohio Christian University`,
    `Ohio University`,
    `Oklahoma State University`,
    `Old Dominion University`,
    `"Old Westbury, SUNY"`,
    `Onondaga Community College`,
    `Ontario Tech University`,
    `Opolska University of Technology`,
    `Oratary Prep School At Summit`,
    `Oregon State University`,
    `Ostbayerische Technische Hochschule Regensburg`,
    `Otterbein University`,
    `Oxford Brookes University`,
    `P.D.A. College of Engineering`,
    `Pace University`,
    `"Pacific University,  Udaipur"`,
    `Palomar College`,
    `Pandit Deendayal Petroleum University`,
    `"Panjab University,  SSG Regional Centre"`,
    `Paramount International School`,
    `Park College of Engineering and Technology`,
    `Parsons School of Design`,
    `Pasadena City College`,
    `"Pascal English School, Cyprus"`,
    `Pathways School Noida`,
    `PDM College of Engineering`,
    `Peirce College`,
    `"Penn State Erie, The Behrend College"`,
    `Pennington School`,
    `Pennsylvania Academy of the Fine Arts`,
    `Perth Amboy Vocational Technical School`,
    `"PES College of Engineering, Mandya"`,
    `PES University`,
    `"PESIT, Bangalore South Campus"`,
    `PGP College of Engineering Technology`,
    `Pima Community College`,
    `Pingree School`,
    `Pittsburgh Technical College - Philadelphia`,
    `Plaksha University`,
    `Plovdiv Medical University`,
    `Pokhara University`,
    `Politecnico di Milano`,
    `Pomona College`,
    `Poornima College of Engineering`,
    `Poornima Group of Institutions`,
    `Port Credit Secondary School`,
    `Porter-Gaud School`,
    `Portland State University`,
    `"Potsdam, SUNY"`,
    `"Presidency School, Surat."`,
    `Preston University`,
    `Princeton Day School`,
    `Princeton International School Of Mathematics And Science`,
    `Princeton University`,
    `Purdue University`,
    `Queen Mary University of London`,
    `Queen's University`,
    `Raksha Shakti University`,
    `Ramapo College of New Jersey`,
    `Randolph-Macon College`,
    `Rani Laxmi Bai Public School`,
    `Raritan Valley Community College`,
    `Rasmussen University`,
    `Ravenscroft School`,
    `Reed College`,
    `REVA University`,
    `Rhode Island College`,
    `Rhode Island School of Design`,
    `Rhodes College`,
    `Rice University`,
    `Richard Stockton University`,
    `Richland College`,
    `Rider University`,
    `Riga Technical University`,
    `RMK College of Engineering`,
    `Robert Gordon University`,
    `Roger Williams University`,
    `Rollins College`,
    `Rosemont College`,
    `Rowan College at Burlington County - Mount Holly`,
    `Rowan College at Burlington County - Pemberton`,
    `Rowan College at Burlington County - Willingboro`,
    `Rowan College at Gloucester County - Mount Laurel`,
    `Rowan University`,
    `"Royal Holloway, University of London"`,
    `RPIIT Technical Campus`,
    `Rudbecksgymnasiet`,
    `"Rungta College of Engineering and Technology, Bhilai"`,
    `Rutgers Preparatory School`,
    `Rutgers University - Newark`,
    `"Rutgers, The State University of New Jersey"`,
    `Ryde School`,
    `Ryerson University`,
    `Saginaw Valley State University`,
    `Sahrdaya College of Engineering and Technology`,
    `Saint Joseph's College of Maine`,
    `Saint Joseph's Preparatory School - Philadelphia`,
    `Saint Joseph's University - Philadelphia`,
    `Saint Paul College`,
    `Saint Peter's Preparatory School`,
    `Saint Peter's University`,
    `Salem Community College`,
    `Salem State University`,
    `San Diego State University`,
    `San Francisco State University`,
    `San Jose State University`,
    `Santa Barbara City College`,
    `Santa Clara University`,
    `Sarvajanik College of Engineering & Technology`,
    `SASTRA University`,
    `Saurashtra University Rajkot`,
    `Savannah State University`,
    `Science Leadership Academy`,
    `Seneca College`,
    `Seton Hall University`,
    `Sharda University`,
    `Sheffield Hallam University`,
    `Sheridan College`,
    `Sherwood Convent School`,
    `Siena College`,
    `Skidmore College`,
    `Slippery Rock University of Pennsylvania`,
    `Slovak University of Technology in Bratislava (STU)`,
    `Smith College`,
    `SOAS University of London`,
    `Society for Development of Composites`,
    `Solebury School`,
    `Sona College of Technology`,
    `South Carolina State University`,
    `South Dakota School of Mines and Technology`,
    `South Hills School of Business & Technology`,
    `South Texas College`,
    `Southeastern Louisiana University`,
    `Southern Connecticut State University`,
    `Southern Illinois University Carbondale`,
    `Southern Illinois University Edwardsville`,
    `Southern Methodist University`,
    `Southern Oregon University`,
    `Southern University and A&M College`,
    `Southern Utah University`,
    `Southwestern College`,
    `Spelman College`,
    `Spelman College`,
    `Spring Arbor University`,
    `Springside Chestnut Hill Academy`,
    `Sree Chitra Thirunal College of Engineering`,
    `Stanford University`,
    `Stanley College of Engineering and Technology for Women`,
    `"Startup Incubation and Innovation Centre, IIT Kanpur"`,
    `Stephen F. Austin State University`,
    `Stetson University`,
    `Stevenson University`,
    `Stockholm University`,
    `Stockton University`,
    `Stonehill College`,
    `"Stony Brook University, SUNY"`,
    `SVS College of Engineering`,
    `Swansea University`,
    `Swarthmore College`,
    `Symbiosis International University`,
    `Syracuse University`,
    `T K M College of Engineering`,
    `Tacoma Community College`,
    `Tallinn University`,
    `Tallinn University of Technology`,
    `Talmudical Yeshiva of Philadelphia`,
    `Tamil Nadu Agricultural University (TNAU)`,
    `Tamilnadu College of Engineering`,
    `Tampere University of Applied Sciences`,
    `Tampere University of Technology`,
    `Tarleton State University`,
    `Teesside University`,
    `Temple University`,
    `Temple University - Ambler`,
    `Temple University - Harrisburg`,
    `Temple University - Health Sciences Campus`,
    `Temple University - Rome`,
    `Temple University - Tokyo`,
    `Tennessee State University`,
    `Texas A&M University`,
    `Texas Christian University`,
    `Texas Southern University`,
    `Texas Southmost College`,
    `Texas State University`,
    `Texas Tech University`,
    `Tezpur University`,
    `The Arts Academy at Benjamin Rush`,
    `The British University In Egypt`,
    `"The City College of New York, CUNY"`,
    `"The College at Brockport, SUNY"`,
    `The College of New Jersey`,
    `The College of Saint Rose`,
    `"The Federal University of Technology,  Akure"`,
    `The George Washington University`,
    `The Governor's School @ Innovation Park`,
    `The Harker School`,
    `The Hill School`,
    `The Katholieke Universiteit Leuven`,
    `The Lawrenceville School`,
    `The Maharaja Sayajirao University of Baroda`,
    `The Mount Tabor Training College`,
    `The Ohio State University`,
    `The Open University`,
    `The Oxford College of Engineering`,
    `The Pennsylvania State University`,
    `The Roxbury Latin School`,
    `The Savannah College of Art and Design`,
    `The SRM University`,
    `The Technical University of Denmark`,
    `The University of Aberdeen`,
    `The University of Akron`,
    `The University of Alabama`,
    `The University of Alabama at Birmingham`,
    `The University of Alberta`,
    `The University of Applied Sciences Upper Austria`,
    `The University of Arizona`,
    `The University of Arkansas`,
    `The University of Bath`,
    `The University of Bedfordshire`,
    `The University of Birmingham`,
    `The University of Bolton`,
    `The University of Bonn`,
    `The University of Bristol`,
    `The University of British Columbia`,
    `The University of Calgary`,
    `The University of Calicut`,
    `"The University of California, Berkeley"`,
    `"The University of California, Davis"`,
    `"The University of California, Irvine"`,
    `"The University of California, Los Angeles"`,
    `"The University of California, Merced"`,
    `"The University of California, Riverside"`,
    `"The University of California, San Diego"`,
    `"The University of California, Santa Barbara"`,
    `"The University of California, Santa Cruz"`,
    `The University of Cambridge`,
    `The University of Central Florida`,
    `The University of Chicago`,
    `The University of Colorado Boulder`,
    `The University of Colorado Colorado Springs`,
    `The University of Connecticut`,
    `The University of Dallas`,
    `The University of Delaware`,
    `The University of Denver`,
    `The University of Derby`,
    `The University of Dundee`,
    `The University of Edinburgh`,
    `The University of Essex`,
    `The University of Evansville`,
    `The University of Exeter`,
    `The University of Falmouth`,
    `The University of Florida`,
    `The University of Georgia`,
    `The University of Glasgow`,
    `The University of Groningen`,
    `The University of Guelph`,
    `The University of Houston`,
    `The University of Huddersfield`,
    `The University of Idaho`,
    `The University of Illinois at Chicago`,
    `The University of Illinois at Urbana-Champaign`,
    `The University of Information Technology and Management in Rzeszow`,
    `The University of Iowa`,
    `The University of Kansas`,
    `The University of Kent`,
    `The University of Kentucky`,
    `The University of La Verne`,
    `The University of Leeds`,
    `The University of Leicester`,
    `The University of Lincoln`,
    `The University of Liverpool`,
    `The University of Ljubljana`,
    `The University of Louisiana at Lafayette`,
    `The University of Louisiana at Monroe`,
    `The University of Louisville`,
    `The University of Manchester`,
    `The University of Manitoba`,
    `"The University of Maryland, Baltimore County"`,
    `"The University of Maryland, College Park"`,
    `The University of Massachusetts Amherst`,
    `The University of Massachusetts Boston`,
    `The University of Massachusetts Dartmouth`,
    `The University of Massachusetts Lowell`,
    `The University of Miami`,
    `The University of Michigan`,
    `The University of Michigan-Dearborn`,
    `The University of Michigan-Flint`,
    `The University of Minnesota`,
    `The University of Mississippi`,
    `The University of Missouri`,
    `The University of Missouri-Kansas City`,
    `The University of Missouri-St. Louis`,
    `The University of Nebraska-Lincoln`,
    `The University of New Brunswick`,
    `The University of New Hampshire`,
    `The University of New Haven`,
    `The University of North Carolina at Chapel Hill`,
    `The University of North Carolina at Charlotte`,
    `The University of North Carolina at Greensboro`,
    `The University of North Texas`,
    `The University of Northampton`,
    `The University of Notre Dame`,
    `The University of Nottingham`,
    `The University of Oklahoma`,
    `The University of Oregon`,
    `The University of Ottawa`,
    `The University of Oulu`,
    `The University of Oxford`,
    `The University of Pennsylvania`,
    `The University of Petroleum and Energy Studies`,
    `The University of Phoenix`,
    `The University of Pittsburgh`,
    `The University of Portland`,
    `The University of Portsmouth`,
    `The University of Richmond`,
    `The University of Rochester`,
    `The University of Salford`,
    `The University of San Francisco`,
    `The University of Sharjah`,
    `The University of Sheffield`,
    `The University of Silesia in Katowice`,
    `The University of South Carolina`,
    `The University of South Florida`,
    `The University of Southampton`,
    `The University of Southern California`,
    `The University of Southern Denmark`,
    `The University of St Andrews`,
    `The University of St. Gallen`,
    `The University of St. Thomas`,
    `The University of Stirling`,
    `The University of Strathclyde`,
    `The University of Stuttgart`,
    `The University of Surrey`,
    `The University of Sussex`,
    `The University of Tampa`,
    `The University of Tennessee`,
    `The University of Texas at Arlington`,
    `The University of Texas at Austin`,
    `The University of Texas at Dallas`,
    `The University of Texas at El Paso`,
    `The University of Texas at San Antonio`,
    `The University of Texas at Tyler`,
    `The University of Texas of the Permian Basin`,
    `The University of Texas Rio Grande Valley`,
    `The University of the District of Columbia`,
    `The University of the District of Columbia`,
    `The University of the Pacific`,
    `The University of the South - Sewanee`,
    `The University of the West Indies`,
    `The University of Toledo`,
    `The University of Toronto`,
    `The University of Toronto Mississauga`,
    `The University of Toronto Scarborough`,
    `The University of Tulsa`,
    `The University of Utah`,
    `The University of Vermont`,
    `The University of Victoria`,
    `The University of Virginia`,
    `The University of Warsaw`,
    `The University of Warwick`,
    `The University of Washington`,
    `The University of Washington Bothell`,
    `The University of Waterloo`,
    `The University of West Georgia`,
    `The University of Western Ontario`,
    `The University of Westminster`,
    `The University of Windsor`,
    `The University of Wisconsin-Eau Claire`,
    `The University of Wisconsin-Green Bay`,
    `The University of Wisconsin-La Crosse`,
    `The University of Wisconsin-Madison`,
    `The University of Wisconsin-Milwaukee`,
    `The University of Wisconsin-Oshkosh`,
    `The University of Wisconsin-Parkside`,
    `The University of Wisconsin-Platteville`,
    `The University of Wisconsin-River Falls`,
    `The University of Wisconsin-Stevens Point`,
    `The University of Wisconsin-Stout`,
    `The University of Wisconsin-Superior`,
    `The University of Wisconsin-Whitewater`,
    `The University of Wolverhampton`,
    `The University of York`,
    `The University of Zagreb`,
    `The Workshop School - Philadelphia`,
    `"Thiagarajar College of Engineering (TCE), Madurai"`,
    `Thomas Edison State College`,
    `Thomas Jefferson University - East Falls (formerly Philadelphia University)`,
    `Thomas Jefferson University - Philadelphia Center City`,
    `Thomas Nelson Community College`,
    `Tongji University`,
    `Towson University`,
    `Trent University`,
    `Trident Academy of Technology`,
    `Trinity College`,
    `Trinity International University`,
    `Trinity Valley School`,
    `Troy University`,
    `Truman State University`,
    `Tshwane University of Technology`,
    `TU/e Technische Universiteit Eindhoven University of Technology`,
    `Tufts University`,
    `Tulane University`,
    `Tunis El Manar University`,
    `Turner Fenton Secondary School`,
    `Ulster University`,
    `Union County College`,
    `Union County Vocational-Technical Schools`,
    `Union University`,
    `United College of Engineering and Research`,
    `University Campus Suffolk`,
    `University College London`,
    `"University College of Engineering and Technology,  Bikaner"`,
    `University of Basel`,
    `"University of Cape Coast, Ghana"`,
    `University of Cincinnati`,
    `University of Cincinnati Clermont College`,
    `University of Duisburg-Essen`,
    `University of Gothenburg`,
    `University of Helsinki`,
    `University of Hull`,
    `University of London`,
    `University of Mary Washington`,
    `University of Maryland University College`,
    `University of North America`,
    `University of North Florida`,
    `University of North Georgia`,
    `"University of Petroleum and Energy Studies (UPES), Dehradun"`,
    `University of Pikeville`,
    `University of Queensland`,
    `University of Regina`,
    `University of Roehampton`,
    `University of Saskatchewan`,
    `University of Science and Technology Houari Boumediene`,
    `University of Southampton`,
    `University of Sunderland`,
    `University of Tartu`,
    `"University of Technology, Jamaica"`,
    `University of the Arts - Philadelphia`,
    `University of the People`,
    `University of the Sciences in Philadelphia`,
    `University of Trento`,
    `University of Udaipur`,
    `University of Valley Forge`,
    `University of Washington Tacoma`,
    `University of West Florida`,
    `"University School of Information, Communication and Technology"`,
    `University Visvesvaraya College of Engineering (UVCE)`,
    `Upper Canada College`,
    `Upper Iowa University`,
    `Ursinus College`,
    `Utah State University`,
    `Utica College`,
    `Utkal University`,
    `Valencia College`,
    `Vanderbilt University`,
    `Vanier College`,
    `Virginia Commonwealth University`,
    `Virginia State University`,
    `Virginia Tech`,
    `Virginia Union University`,
    `Virginia University of Lynchburg`,
    `Wake Forest University`,
    `Wake Technical Community College`,
    `Walchand College of Engineering`,
    `Walnut Hill College`,
    `Wardlaw + Hartridge School`,
    `Warsaw School of Economics`,
    `Warsaw University of Technology`,
    `Wartburg College`,
    `Washington and Lee University`,
    `Washington State University`,
    `Washington University in St. Louis`,
    `Wayne State University`,
    `Wellesley College`,
    `Wellington C. Mepham Highschool`,
    `Wells College`,
    `Wesleyan University`,
    `West Chester University`,
    `Westdale Secondary School`,
    `Western Carolina University`,
    `Western Connecticut State University`,
    `Western Governors University`,
    `Western Kentucky University`,
    `Western Michigan University`,
    `Western New England University`,
    `Western Technical College`,
    `Western University`,
    `Western Washington University`,
    `Westminster College`,
    `Westminster School`,
    `Whitworth University`,
    `Wichita State University`,
    `Widener University`,
    `Wilfrid Laurier University`,
    `Wilkes University`,
    `William & Mary`,
    `William Paterson University`,
    `Williams College`,
    `Williamson Free School of Mechanical Trades`,
    `Wilmington University`,
    `Wiltshire College`,
    `Winona State University`,
    `Winthrop University`,
    `Worcester State University`,
    `Wright State University`,
    `Xavier University`,
    `Yale University`,
    `Yale-NUS College`,
    `Yeshiva University`,
    `York College of Pennsylvania`,
    `"York College, CUNY"`,
    `York University`,
    `Youngstown State University`,
].map(w => w.replace(/['"]+/g, '')).sort()
